name: Deploy GCF

on:
  push:
    branches: [master]

jobs:
    
  deploy-gcf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: 'GCP Auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_JSON_KEY }}'
      
      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.6.0
      
      - name: Deploy to Cloud Run
        run: |
          gcloud functions deploy ${{ github.event.repository.name }} \
          --region=asia-southeast1 \
          --source=. \
          --entry-point=webhook \
          --trigger-http \
          --runtime=python312 \
          --service-account=${{ github.event.repository.name }}@test-gold-price.iam.gserviceaccount.com \
          --security-level=SECURE_ALWAYS \
          --timeout=540s